name: Upload S3
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  upload-s3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Upload
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --follow-symlinks --delete --exclude '*' --include 'dapps/*' --include 'blockchains/*'
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'ca-central-1'
